你好，我是吴咏炜。

到现在为止，我们已经有好多次都提到异常了。今天，我们就来彻底地聊一聊异常。

首先，开宗明义，如果你不知道到底该不该用异常的话，那答案就是该用。如果你需要避免使用异常，原因必须是你有明确的需要避免使用异常的理由。

下面我们就开始说说异常。

## 没有异常的世界

我们先来看看没有异常的世界是什么样子的。最典型的情况就是 C 了。

假设我们要做一些矩阵的操作，定义了下面这个矩阵的数据结构：

```c
typedef struct {
  float* data;
  size_t nrows;
  size_t ncols;
} matrix;
```

我们至少需要有初始化和清理的代码：

```c
enum matrix_err_code {
  MATRIX_SUCCESS,
  MATRIX_ERR_MEMORY_INSUFFICIENT,
  …
};

int matrix_alloc(matrix* ptr,
                 size_t nrows,
                 size_t ncols)
{
  size_t size =
    nrows * ncols * sizeof(float);
  float* data = malloc(size);
  if (data == NULL) {
    return MATRIX_ERR_MEMORY_INSUFFICIENT;
  }
  ptr->data = data;
  ptr->nrows = nrows;
  ptr->ncols = ncols;
}

void matrix_dealloc(matrix* ptr)
{
  if (ptr->data == NULL) {
    return;
  }
  free(ptr->data);
  ptr->data = NULL;
  ptr->nrows = 0;
  ptr->ncols = 0;
}
```
<div><strong>精选留言（30）</strong></div><ul>
<li><img src="https://static001.geekbang.org/account/avatar/00/16/bc/25/1c92a90c.jpg" width="30px"><span>tt</span> 👍（43） 💬（5）<div>文中下面的一句话：

“首先是内存分配。如果 new 出错，按照 C++ 的规则，一般会得到异常 bad_alloc，对象的构造也就失败了。这种情况下，在 catch 捕捉到这个异常之前，所有的栈上对象会全部被析构，资源全部被自动清理。”

谈的是new在分配内存时的错误，是堆上内存的错误，但自动被析构的却是栈上的对象。一开始我想是不是笔误了，但仔细想想，堆上的东西都是由栈上的变量所引用的，栈上对象析构的过程，堆上相应的资源自然就被释放了。而且被释放的对象的范围还被栈帧限定了。</div>2019-12-09</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/12/fe/6b/81b2e40a.jpg" width="30px"><span>亮</span> 👍（31） 💬（1）<div>看到老师说了部分开源的异常优秀的C++开源项目，老师能否推荐些现在流行的，能逐步深入的网络编程方面的C++开源项目看呢，从入门到深入的都推荐一些吧。谢谢老师</div>2019-12-17</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/fb/2d/e6548e48.jpg" width="30px"><span>tokamak</span> 👍（22） 💬（1）<div>老师，你好。目前主流的开源项目中，有没有使用了异常的优秀的C++开源项目？可以用来作为参考案例。</div>2019-12-13</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/f4/ae/3b101c00.jpg" width="30px"><span>fl260919784</span> 👍（6） 💬（1）<div>老师好，有没有编译器平台对异常的实现原理的资料呢，比如X86下G++ -S会发现安插了一些__cxa_throw之类的调用，感谢</div>2020-02-17</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/16/f3/ea/2b2adda5.jpg" width="30px"><span>EncodedStar</span> 👍（6） 💬（2）<div>一、使用异常
1.异常处理并不意味着需要写显示的try和catch。异常安全的代码，可以没有任何try和catch
2.适当组织好代码，利用好RAII，实现矩阵的代码和使用矩阵的代码都可以更短、更清晰，处理异常一般情况会记日志或者向外界用户报告错误。
二、使用异常的理由
1.vector C++标准容器中提供了at成员函数，能够在下标不存在的时候抛出异常(out_of_range)，作为一种额外的帮助调试手段
2.强异常保证，就是一旦异常发生，现场会恢复到调用异常之前的状态。(vector在元素类型没有提供保证不抛异常的移动构造函数的情况下，在移动元素时会使用拷贝构造函数，一旦某操作发生异常，就可以恢复原来的样子)
3.只要使用标准容器就都的处理可能引发的异常bad_alloc
4。可以使用异常，也可以使用assert
课后思考
你的C++项目里使用过异常吗？为什么？
答：按老师课里说的，只要使用了标准容器就得考虑使用处理异常(bad_alloc)，所以，大部分C++代码如果保证安全的情况下都的考虑这个异常。当然也在别的地方，之前在读取配置文件(json文件)字段的时候加过，如果读取失败，异常抛出
</div>2019-12-22</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/14/33/e7/145be2f9.jpg" width="30px"><span>怪兽</span> 👍（4） 💬（1）<div>异常真是一个大话题，请假老师2个疑问点：
1. 函数标不标noexcept有什么区别？标了noexcept，表示不会抛出异常，也就表示异常安全吗？异常安全的代码也就不需要try和catch了 。但实际上，不管函数有没有标noexcept，如果确实抛出了异常，就会调用std::terminate。所以总的来说，函数标了noexcept只是一种声明而已，是想告诉编译器它是安全的，可以被move或其他优化，老师这样理解对吗？
2. 看评论说，析构函数缺省就是noexcept，那么构造函数缺省也是noexcept的吗？有必要标noexcept吗？</div>2021-06-09</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/db/64/06d54a80.jpg" width="30px"><span>中年男子</span> 👍（4） 💬（3）<div>用到异常的时候倒不是很多，但是异常千万别乱用，害人害己，
曾经同事离职，接手他项目的代码，把我坑的，几乎所有能引起crash的地方都用try catch 捕获异常，然而不处理异常，比如非法指针， 这种bug居然用try catch 来规避，坑了我两个月时间才把程序搞稳定了，现在想起他来，心里还有一句mmp想送给他。。。</div>2019-12-09</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/18/9d/ab/6589d91a.jpg" width="30px"><span>林林</span> 👍（3） 💬（1）<div>为什么说“异常处理并不意味着需要写显式的 try 和 catch”    没有catch的话，程序不是会挂掉吗？</div>2021-03-26</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/14/33/e7/145be2f9.jpg" width="30px"><span>怪兽</span> 👍（2） 💬（1）<div>老师打扰一下，请教2点疑惑：
1. 原文中描述：“C++ 的标准容器在大部分情况下提供了强异常保证，即，一旦异常发生，现场会恢复到调用函数之前的状态，容器的内容不会发生改变，也没有任何资源泄漏。”

既然是强异常保证下发生异常，此时不就立即调用std::terminate结束程序了？还需要在意现场有没有恢复？容器的内容有没有发生变化？

2. 原文中描述：“只要你使用了标准容器，不管你自己用不用异常，你都得处理标准容器可能引发的异常——至少有 bad_alloc”

这应该是容器在分配内存时，并不是异常安全的，才会抛出的bad_alloc异常吧？如果分配内存是异常安全的，当发生异常抛出bad_alloc时，就立即std::terminate结束程序了，这样理解对吗？</div>2021-09-18</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/1d/b4/7c/62c1b9bd.jpg" width="30px"><span>Minghao</span> 👍（2） 💬（1）<div>你好老师，学习了06异常和07迭代器，也自己写了一遍smart_pointer和istream_line_reader。您在课中提到了 “vector 会在元素类型没有提供保证不抛异常的移动构造函数的情况下，在移动元素时会使用拷贝构造函数“。我想请教一下，在自己开发的过程中，一般哪些成员函数需要考虑添加noexcept关键字呢？</div>2020-05-27</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/qrLibiczMaSJfmMuvA1ZqILyhNsuphAcQG8wX1iajTibXU26kmQoGejRGXh8RNK1q3zaaibcfpujrVIYkRlMy5XF6Vw/132" width="30px"><span>李蔚韬</span> 👍（2） 💬（5）<div>老师，对于异常的第一条批评我不太理解，什么叫“只要开启异常，即使不使用”，这里的开启是指什么呢？</div>2019-12-09</li><br/><li><img src="https://thirdwx.qlogo.cn/mmopen/vi_32/NyFOEueITjaGLpakMEuWAqVQjo1uDIXlpDdpCxXGfaWiaXzibLQ3WgOFCe8D9FvCmyjsGT7jDsLUbkt8jt2aVs9g/132" width="30px"><span>geek</span> 👍（1） 💬（1）<div>老师，我理解RAII也并不是完全自动的，如果最顶层函数都没有try catch块的话，程序还是会异常结束，伴随着可能存在资源没释放的情况。RAII + 至少一个有效的try catch块 才能保证出现异常时，资源也会正确释放吧。</div>2021-02-22</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/12/41/c0/910c4834.jpg" width="30px"><span>what are you up</span> 👍（1） 💬（1）<div>析构函数没法抛出异常吗？</div>2020-09-07</li><br/><li><img src="" width="30px"><span>Fiery</span> 👍（1） 💬（1）<div>习惯了python和golang支持的多返回值，会感觉返回错误码很方便，只要把错误码作为第二个返回值就好了，只不过c++默认只支持一个返回值，想返回多个值还要显示的调用std::tie，要是可以直接支持多返回值的话，就不会这么纠结了吧？</div>2020-03-23</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/37/4a/a2/4ff26e2c.jpg" width="30px"><span>寒先森</span> 👍（0） 💬（1）<div>老师，如果一个项目混合了C、C++、Python，应该怎么协调统一不同语言之间的错误处理方式呢？</div>2024-01-09</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/16/a0/57/3a729755.jpg" width="30px"><span>灯盖</span> 👍（0） 💬（1）<div>项目中有使用异常。多层函数的嵌套，异常信号的传递都是在这个过程中需要考虑的问题。异常，bool返回值，错误码，assert这些手段目前在项目中都有存在。怎样是一个比较好的状态，还需要摸索。</div>2023-02-07</li><br/><li><img src="" width="30px"><span>anotherS</span> 👍（0） 💬（1）<div>&quot;1.异常处理并不意味着需要写显式的 try 和 catch。2.异常安全的代码，可以没有任何 try 和 catch。&quot;
这个可以举个例子吗？
1. 不显示的写是说还有隐式的什么操作吗？
2. 异常安全的代码，异常安全指在发生异常时，既不会发生资源泄漏，系统也不会处于一个不一致的状态。但是还是有异常发生并且抛出了，如果没有try cache ，那不是崩了？崩了都不try吗？
</div>2022-06-14</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/13/4b/1b/e3b3bcff.jpg" width="30px"><span>jcy</span> 👍（0） 💬（1）<div>明白了，大概理解是使用异常代码更简洁优雅，非特殊场景使用异常更好

另 第一次定义 class matrix 的地方最后少了个 ; 号</div>2022-04-13</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/14/33/e7/145be2f9.jpg" width="30px"><span>怪兽</span> 👍（0） 💬（1）<div>老师又打扰一下，原文中“特殊成员（构造函数、析构函数、赋值函数等）会自动成为 noexcept，如果它们调用的代码都是 noexcept 的话。”那么返过来呢？例如赋值函数标noexcept，而赋值函数中调用的swap函数没有noexcept，那么最终会是什么效果？</div>2021-06-11</li><br/><li><img src="https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eqf54z1ZmqQY1kmJ6t1HAnrqMM3j6WKf0oDeVLhtnA2ZUKY6AX9MK6RjvcO8SiczXy3uU0IzBQ3tpw/132" width="30px"><span>Geek_68d3d2</span> 👍（0） 💬（3）<div>总结：程序在编写过程中总会有不正常的情况，处理不正常的情况要么使用错误码各种if&#47;else 还要预防在构造函数里出现不正常现象，要么使用异常，在异常出现后进行try catch最终保证程序无内存泄漏且功能一致。</div>2020-06-08</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/1c/34/9a/1587bc6f.jpg" width="30px"><span>JDY</span> 👍（0） 💬（1）<div>老师您好，我请教一个很基础的题外问题，在这个初始化函数中，我们为什么不传递一个matrix ptr，然后用ptr.data 呢？很小的问题，希望您能回答一下，谢谢了~
int matrix_alloc(matrix* ptr, size_t nrows, size_t ncols){
    .....
   ptr -&gt; data = data;
}</div>2020-02-26</li><br/><li><img src="" width="30px"><span>tr</span> 👍（0） 💬（1）<div>“异常比较隐蔽，不容易看出来哪些地方会发生异常和发生什么异常。”
老师，一般来说是不是都采用错误码+异常的方式来处理这种问题。接口内部抛出异常并处理异常，对外返回错误码，调用接口的人就不用考虑接口内部抛出的异常？</div>2020-01-25</li><br/><li><img src="" width="30px"><span>tr</span> 👍（0） 💬（1）<div>老师，为什么vector让operator[]是noexcept，是为了性能么？然后at用来调试？</div>2020-01-24</li><br/><li><img src="" width="30px"><span>Terry</span> 👍（0） 💬（2）<div>如果new失败，抛出异常不处理，程序不会crash吗</div>2020-01-22</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/11/7b/8a/c411a123.jpg" width="30px"><span>执假以为真</span> 👍（0） 💬（1）<div>个人所见的年销售额数亿美元产品的工业级代码里确实没见到异常，也许如文中所述的原因及历史原因吧。但有什么知名产品的C++代码或著名开源项目是使用了异常的吗？</div>2020-01-12</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTItaas8rpvXb70zfjMetkEuYeLH0rI348MCaKqyn9HAbGZsdCKibLTnfGEBMbwQLBOhPMROcVBk9vA/132" width="30px"><span>不谈</span> 👍（0） 💬（1）<div>作为java程序员刚开始对于C++这种规则完全不能理解，看了文章之后又理解了，不使用异常是有道理的。现在理解了vector 会在元素类型没有提供保证不抛异常的移动构造函数的情况下，在移动元素时会使用拷贝构造函数这句话的含义了。C++就是这么与众不同</div>2019-12-17</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/11/2e/6e/05230eb6.jpg" width="30px"><span>稻草人的忧桑</span> 👍（0） 💬（1）<div>请问libbreakpad跟underflow_error有关联么？现在使用breakpad捕获异常，有很多underflow_error的信息</div>2019-12-13</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/11/2e/6e/05230eb6.jpg" width="30px"><span>稻草人的忧桑</span> 👍（0） 💬（1）<div>请问underflow_error 什么情况下会抛出？</div>2019-12-11</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/c4/eb/2285a345.jpg" width="30px"><span>花晨少年</span> 👍（0） 💬（1）<div>C++ 虽然支持运算符重载，可你也不能使用，因为你没法返回一个新矩阵……
不太理解这句话的意思，是用运算符来替换构造函数吗，运算符为啥不能返回新矩阵？</div>2019-12-11</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/r0fibSY02VITyVkSxD0nOLSSf1kK3MAYHRJQgobibN2CShXOJMzwQuP7qXLH7cbrDibzw3C5fBFiaIRZwdACHTaxgg/132" width="30px"><span>neilyu</span> 👍（0） 💬（1）<div>C++ 虽然支持运算符重载，可你也不能使用，因为你没法返回一个新矩阵……
&#47;&#47;请问这句话怎么理解？为啥不能返回一个新矩阵呢？</div>2019-12-10</li><br/>
</ul>