你好，我是景霄。

今天这节课，我想和你聊聊Python的异常处理。和其他语言一样，异常处理是Python中一种很常见，并且很重要的机制与代码规范。

我在实际工作中，见过很多次这样的情况：一位工程师提交了代码，不过代码某处忘记了异常处理。碰巧这种异常发生的频率不低，所以在代码push到线上后没多久，就会收到紧急通知——服务器崩溃了。

如果事情严重，对用户的影响也很大，这位工程师还得去专门的会议上做自我检讨，可以说是很惨了。这类事件层出不穷，也告诉我们，正确理解和处理程序中的异常尤为关键。

## **错误与异常**

首先要了解，Python中的错误和异常是什么？两者之间又有什么联系和区别呢？

通常来说，程序中的错误至少包括两种，一种是语法错误，另一种则是异常。

所谓语法错误，你应该很清楚，也就是你写的代码不符合编程规范，无法被识别与执行，比如下面这个例子：

```
if name is not None
    print(name)
```

If语句漏掉了冒号，不符合Python的语法规范，所以程序就会报错`invalid syntax`。

而异常则是指程序的语法正确，也可以被执行，但在执行过程中遇到了错误，抛出了异常，比如下面的3个例子：

```
10 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero

order * 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'order' is not defined

1 + [1, 2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

它们语法完全正确，但显然，我们不能做除法时让分母为0；也不能使用未定义的变量做运算；而让一个整型和一个列表相加也是不可取的。
<div><strong>精选留言（30）</strong></div><ul>
<li><img src="https://static001.geekbang.org/account/avatar/00/17/51/ea/d9a83bb3.jpg" width="30px"><span>古明地觉</span> 👍（172） 💬（6）<div>老师，看到异常这一讲，忽然想起了一个问题，一直困扰着我
e = 1
try:
    1 &#47; 0
except ZeroDivisionError as e:
    pass

print(e)  # NameError: name &#39;e&#39; is not defined
这里为什么会显示e没有被定义呢？</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/13/f1/21/52e8267b.jpg" width="30px"><span>Hoo-Ah</span> 👍（95） 💬（2）<div>第一种写法更加简洁，易于阅读。而且except后面的错误类型先抛出数据库连接错误，之后才抛出查询错误，实现的异常处理和第二种一样。</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/23/93/d6cd8897.jpg" width="30px"><span>liput</span> 👍（17） 💬（3）<div>想请问老师，在facebook里面开发，对于异常处理有什么规范需要遵循吗？自定义异常、抛异常、捕获异常，粒度一般怎么把控呢？
与此相应的，我对日志输出也有同样的疑问，希望老师能结合您在大公司里的实战经验多讲讲。</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/17/4b/53/67c08006.jpg" width="30px"><span>John Si</span> 👍（4） 💬（1）<div>1. 第一種寫法比第二種寫法簡潔
2. 因我對try語法執行流程不太清楚，還是老師跟熟悉該同學多講解一下。但我自己想法是第二種寫法跟巢狀迴圈寫法很像，假設是第二句語法發生錯誤，第二種寫法會多執行一次try 語句，從而增加了程序運行時間。

綜上所述，我認為第一種寫法較第二種好</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/14/8a/db/76ab84c6.jpg" width="30px"><span>小豹子</span> 👍（3） 💬（1）<div>老师，系统异常，非系统异常能举个例子说明下吗？</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/1d/5b/13/6db9ba58.jpg" width="30px"><span>Kevin</span> 👍（1） 💬（1）<div>从代码行数看第一种更简洁，第一种中，使用了一个try..expect将异常统一处理，代码简洁，
第二种，代码中有嵌套，</div>2020-06-17</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/11/c1/46/a81f7402.jpg" width="30px"><span>王大华</span> 👍（1） 💬（2）<div>第一种和第二种效果类似，
都是先检查数据库连接异常，再检查query执行的异常。

更喜欢这种写法：
try:
    db = DB.connect(&#39;&lt;db path&gt;&#39;) # 可能会抛出异常
    raw_data = DB.queryData(&#39;&lt;viewer_id&gt;&#39;) # 可能会抛出异常
except DBConnectionError as err:
    print(&#39;ConnectionError: {}&#39;.format(err))
except DBQueryDataError as err:
    print(&#39;QueryDataError: {}&#39;.format(err))</div>2020-02-02</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/18/26/dd/d58156b1.jpg" width="30px"><span>一粒</span> 👍（1） 💬（1）<div>老师，什么样的代码才是您说的“flow-control”</div>2020-01-02</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/1c/f4/f7/871ff71d.jpg" width="30px"><span>Geek_David</span> 👍（0） 💬（1）<div>个人觉得这个课还要加上一本python的书，那就天衣无缝了</div>2020-03-29</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/17/4a/27/2702206d.jpg" width="30px"><span>百年</span> 👍（0） 💬（1）<div>老师的课收获比较大，Python基础课也学过，Python核心机制也学过一点，但是一写代码，特别是实时读写文件，总是报一大堆错误，这结课真的是运用上了。</div>2019-05-29</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/98/9e/6185004a.jpg" width="30px"><span>Blackwang</span> 👍（0） 💬（2）<div>第一种更好，不过理由说不上来……
另外老师，请问前几天思考题的答案有吗？之前说周末放 github 的？</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/11/c7/c6/35cc7c7c.jpg" width="30px"><span>Robert小七</span> 👍（0） 💬（1）<div>为什么不直接用except Exception as err?</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/16/f5/9f/1509d389.jpg" width="30px"><span>栾~龟虽寿！</span> 👍（0） 💬（3）<div>老师，课越听越觉得值，可是大家如何在手机上写代码的？不会是电脑上写好，利用微信，转发给自己手机上，再复制粘贴到留言吧？还有我有些着急，是否能一天播放两课，哈哈，我有基础。</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/12/55/55/19ec7b0e.jpg" width="30px"><span>mickle</span> 👍（0） 💬（1）<div>我在开发中用第一种吧，第二种代码冗余，看着难受</div>2019-05-27</li><br/><li><img src="" width="30px"><span>Geek_b6f316</span> 👍（35） 💬（1）<div>第一种方法简单明了，是不是少了一个as</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/13/7c/8a/bdeb76ac.jpg" width="30px"><span>Fergus</span> 👍（23） 💬（0）<div>选择1，原因有2：
1. 从开始学就如①这么写的；
2. ②读起来太难受，太不pythonic；

读了留言后意识到：
3. ①与②的运行逻辑一致，①可以看作②的简化版；
4. ②的写法，如出现异常，多次调用异常处理，降低程序运行效率；

多谢小伙伴们👍</div>2019-05-28</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/14/2a/94/8c128d36.jpg" width="30px"><span>Howard</span> 👍（10） 💬（0）<div>1, 2我还是有点纠结，虽然明显第1优于2，但是2有一个好处就是可以根据错误定义自己的异常信息。所以个人觉得第3种更好。

try:
    db = DB.connect(&#39;&lt;db path&gt;&#39;)
    raw_data = DB.queryData(&#39;&lt;viewer_id&gt;&#39;)
except DBConnectionError as err:
    print(&#39;DB connection failed {}&#39;.format(err))
except DBQueryDataError as err:
    print(&#39;DB query failed {}&#39;.format(err))</div>2019-10-24</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/12/4e/d1/ded6b849.jpg" width="30px"><span>大飞守角</span> 👍（5） 💬（0）<div>思考题： 第一种比较好，第二种多层嵌套

还有，文章中举的例子，字典我一般获取使用 d.get(&quot;bob&quot;, None)这种方式，不会报异常，没有直接返回None</div>2019-07-11</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/17/42/b0/687e13d0.jpg" width="30px"><span>太平湖-燃气（DUYANG）18356257898</span> 👍（5） 💬（2）<div>什么是flow-control。。</div>2019-05-31</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/17/92/47/ce146561.jpg" width="30px"><span>yllopy</span> 👍（4） 💬（0）<div>在用finally中用f.close()前建议加上一条判断：if ‘f’ in locals() 用以避免在f被赋值前发生异常而没有被定义导致的二次异常。</div>2019-06-03</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/88/21/50b2418a.jpg" width="30px"><span>alan</span> 👍（4） 💬（1）<div>老师好，相比try-catch的错误处理模式，您觉得Golang那样的返回error的错误处理方式怎么样？您更喜欢哪种错误处理方式？</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/cc/c4/5ac16f31.jpg" width="30px"><span>汤尼房</span> 👍（3） 💬（1）<div>第一种方式会更好，try代码段中的代码按顺序执行，若db = DB...这行代码抛出异常，则except语句将会捕获该异常，代码将直接跳转到except代码段中，而raw_data = DB...则不会被执行。若db = DB...没抛出异常，而raw_data抛出异常，except语句依然会将抛出的异常捕获。所以当try block中有多处抛出异常时，第二种方式并不会一次执行均会将所有存在的异常都抛出来，而是和第一种方式一样的线性执行，遇到异常，except便会将其捕获，出现异常语句后面的语句则不会再执行。因此，两者效果是一样的，且第一种方式显得更加有条理，更加简洁，清晰，所以觉得第一种方式会更好一些。</div>2019-05-28</li><br/><li><img src="http://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJDFSUdfgwWZf7fRxTfmyx3TsKL7ZjegELDoXjmZCvLrVLgUp1goR3RVfhH2chjwLb22wpXSsfRWQ/132" width="30px"><span>Geek_41743c</span> 👍（2） 💬（0）<div>dict取值是不是用get()比较好。</div>2019-05-28</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/bc/29/022905e6.jpg" width="30px"><span>SCAR</span> 👍（2） 💬（0）<div>应该是第一种情况更优：
1. 从实现的功能来看第一种和第二种都能达到，不过程序里两种异常是线性依次的，所以完全可以并行写在一个except里，再者python里的标准异常都__str__处理过，是完全可以区分哪个异常发生的。
2. 但就像the zen of python里强调的那样，简单和清晰是 python代码应该遵从的，显然第一种更优。</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/0f/a4/5a/e708e423.jpg" width="30px"><span>third</span> 👍（2） 💬（0）<div>小白提问
针对06思考的第一问，分次读取文件
读取完成一个很大的文件之后，这些文件存放在哪里？
如果这个文件大到了无法一次读取内存，那么他是否应该存储在磁盘中？在需要用的时候，又从磁盘中调取呢？
希望老师解释一下</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/14/38/d7/de6832df.jpg" width="30px"><span>Python高效编程</span> 👍（2） 💬（0）<div>第一种方式清晰一点</div>2019-05-27</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/1d/1b/1e/f5c16f7e.jpg" width="30px"><span>单色</span> 👍（1） 💬（0）<div>思考题：
第一种更好，简洁明了。


异常，通常是指程序运行的过程中遇到了错误，终止并退出。我们通常使用 try except 语句去处理异常，这样程序就不会被终止，仍能继续执行。
处理异常时，如果有必须执行的语句，比如文件打开后必须关闭等等，则可以放在 finally  block 中。
异常处理，通常用在你不确定某段代码能否成功执行，也无法轻易判断的情况下，比如数据库的连接、读取等等。正常的 flow-control 逻辑，不要使用异常处理，直接用条件语句解决就可以了。</div>2020-03-29</li><br/><li><img src="" width="30px"><span>Paul Shan</span> 👍（1） 💬（0）<div>异常是正常的反面，是程序代码非常规路径的跳转，是我初学编程时避之不及的类型。随着编程经验的增加，这种多处跳转，一处处理的模式有其价值。
我个人觉得静态语言处理简单的错误状态更为高效简洁。例如kotlin语言引入了nullable类型以后，对于创建型的函数可以用null来代表错误状态，这样可以在编译阶段强制处理主要的错误状态。</div>2019-11-14</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/dd/09/feca820a.jpg" width="30px"><span>helloworld</span> 👍（1） 💬（2）<div>老师，对文中的自定义异常不太理解，为什么要主动去raise自定义异常，有啥意义吗</div>2019-05-29</li><br/><li><img src="https://static001.geekbang.org/account/avatar/00/10/42/d7/1f1634af.jpg" width="30px"><span>无才不肖生</span> 👍（1） 💬（0）<div>老师，想问个题外题
对象的属性是个字典，django中要根据属性里字典的某个键值查询该怎么做呢，如下面的，我想直接根据companyType来查询过滤记录
person
{
    IDCard:12345678901,
    name:emily
    companys：
        companyName:&#39;阿里&#39;,
        companyType:&#39;电商&#39;
}</div>2019-05-28</li><br/>
</ul>